/**
 * Model Viewer Page
 * Displays financial model with Excel-grade formatting
 */

import { notFound } from 'next/navigation';
import prisma from '@/lib/db';
import { getViewerSheets } from '@/lib/viewer';
import ViewerGrid from './ViewerGrid';

interface PageProps {
  params: Promise<{ snapshotId: string }>;
}

export default async function ViewerPage({ params }: PageProps) {
  const { snapshotId } = await params;

  // Get snapshot metadata
  const snapshot = await prisma.modelSnapshot.findUnique({
    where: { id: snapshotId },
    include: {
      entity: true,
      _count: {
        select: { outputLines: true, viewerSheets: true },
      },
    },
  });

  if (!snapshot) {
    notFound();
  }

  // Get viewer sheets
  const viewerSheets = await getViewerSheets(snapshotId);

  if (viewerSheets.length === 0) {
    return (
      <div className="p-8">
        <h1 className="text-2xl font-bold mb-4">Model Viewer</h1>
        <div className="bg-yellow-50 border border-yellow-200 rounded p-4">
          <p className="text-yellow-800">
            No viewer sheets found for this snapshot. Please generate them first.
          </p>
          <p className="text-sm text-yellow-600 mt-2">
            Run BuildViewerSheetsJob with snapshotId: {snapshotId}
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-8 py-6">
        <h1 className="text-3xl font-bold text-gray-900">
          {snapshot.entity?.displayName || 'Financial Model'}
        </h1>
        <div className="mt-2 flex gap-6 text-sm text-gray-600">
          <span>
            Snapshot: <span className="font-mono">{snapshotId.slice(0, 16)}...</span>
          </span>
          <span>
            Engine: <span className="font-medium">{snapshot.calcEngineVersion}</span>
          </span>
          <span>
            Created: {new Date(snapshot.createdAt).toLocaleString()}
          </span>
          <span>
            Output Lines: <span className="font-medium">{snapshot._count.outputLines}</span>
          </span>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white border-b border-gray-200">
        <div className="px-8">
          <nav className="flex gap-4">
            {viewerSheets.map((sheet) => (
              <a
                key={sheet.sheetName}
                href={`#${sheet.sheetName}`}
                className="px-4 py-3 text-sm font-medium text-gray-700 border-b-2 border-transparent hover:border-blue-500 hover:text-blue-600"
              >
                {sheet.sheetName}
              </a>
            ))}
          </nav>
        </div>
      </div>

      {/* Sheets */}
      <div className="px-8 py-6 space-y-8">
        {viewerSheets.map((sheet) => (
          <div key={sheet.sheetName} id={sheet.sheetName}>
            <ViewerGrid sheet={sheet} />
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="bg-white border-t border-gray-200 px-8 py-4 text-center text-sm text-gray-500">
        Generated by FMWP v{snapshot.calcEngineVersion}
      </div>
    </div>
  );
}
